--SELECT A.BRA_CODE,A.TEAM_NO,A.TEAM_NAME,A.*  FROM ACT_TEAM A WHERE TEAM_NO =130

create or replace PROCEDURE RM_SETUP_MGRS
AS
 CURSOR c0_loan_mas1
    IS
        SELECT  A.ACCT_MGR,A.BRA_CODE,A.TEAM_NO,A.MGR_NAME,A.DEP_CODE,A.AUT_AMT_DR,A.AUT_AMT_CR,A.AUT_LVL,A.MAT_DATE
        FROM ACCT_MGR A
        WHERE MGR_NAME NOT IN ('VACANT');
        --AND ACCT_MGR IN (1301,1701,1921,1901);

Customer_1  number;
Counter     number;

BEGIN
    FOR c0rec IN c0_loan_mas1
    LOOP
 --201
  IF c0rec.BRA_CODE <> 201
    THEN    
        BEGIN
        INSERT INTO ACCT_MGR (ACCT_MGR,BRA_CODE,TEAM_NO,MGR_NAME,DEP_CODE,AUT_AMT_DR,AUT_AMT_CR,AUT_LVL,MAT_DATE,SEC_CODE,ALT_ACCT_MGR1,ALT_ACCT_MGR2,ALT_ACCT_MGR3,DEL_DATE,TELL_ID,UPD_TIME)
        VALUES (c0rec.ACCT_MGR,201,c0rec.TEAM_NO,c0rec.MGR_NAME,8,0,0,100,'22-oct-2017',0,'','','','',1187,93844);EXCEPTION
        WHEN OTHERS THEN NULL;
    COMMIT;
    END;
    END IF;
    

 --999
  IF c0rec.BRA_CODE <> 999
    THEN    
        BEGIN
        INSERT INTO ACCT_MGR (ACCT_MGR,BRA_CODE,TEAM_NO,MGR_NAME,DEP_CODE,AUT_AMT_DR,AUT_AMT_CR,AUT_LVL,MAT_DATE,SEC_CODE,ALT_ACCT_MGR1,ALT_ACCT_MGR2,ALT_ACCT_MGR3,DEL_DATE,TELL_ID,UPD_TIME)
        VALUES (c0rec.ACCT_MGR,999,c0rec.TEAM_NO,c0rec.MGR_NAME,8,0,0,100,'22-oct-2017',0,'','','','',1187,93844);EXCEPTION
        WHEN OTHERS THEN NULL;
    COMMIT;
    END;
    END IF;
    
    --211
  IF c0rec.BRA_CODE <> 211
    THEN    
        BEGIN
        INSERT INTO ACCT_MGR (ACCT_MGR,BRA_CODE,TEAM_NO,MGR_NAME,DEP_CODE,AUT_AMT_DR,AUT_AMT_CR,AUT_LVL,MAT_DATE,SEC_CODE,ALT_ACCT_MGR1,ALT_ACCT_MGR2,ALT_ACCT_MGR3,DEL_DATE,TELL_ID,UPD_TIME)
        VALUES (c0rec.ACCT_MGR,211,c0rec.TEAM_NO,c0rec.MGR_NAME,8,0,0,100,'22-oct-2017',0,'','','','',1187,93844);EXCEPTION
        WHEN OTHERS THEN NULL;
    COMMIT;
    END;
    END IF;

--212
  IF c0rec.BRA_CODE <> 212
    THEN    
        BEGIN
        INSERT INTO ACCT_MGR (ACCT_MGR,BRA_CODE,TEAM_NO,MGR_NAME,DEP_CODE,AUT_AMT_DR,AUT_AMT_CR,AUT_LVL,MAT_DATE,SEC_CODE,ALT_ACCT_MGR1,ALT_ACCT_MGR2,ALT_ACCT_MGR3,DEL_DATE,TELL_ID,UPD_TIME)
        VALUES (c0rec.ACCT_MGR,212,c0rec.TEAM_NO,c0rec.MGR_NAME,8,0,0,100,'22-oct-2017',0,'','','','',1187,93844);EXCEPTION
        WHEN OTHERS THEN NULL;
    COMMIT;
    END;
    END IF;
    
--214
  IF c0rec.BRA_CODE <> 214
    THEN    
        BEGIN
        INSERT INTO ACCT_MGR (ACCT_MGR,BRA_CODE,TEAM_NO,MGR_NAME,DEP_CODE,AUT_AMT_DR,AUT_AMT_CR,AUT_LVL,MAT_DATE,SEC_CODE,ALT_ACCT_MGR1,ALT_ACCT_MGR2,ALT_ACCT_MGR3,DEL_DATE,TELL_ID,UPD_TIME)
        VALUES (c0rec.ACCT_MGR,214,c0rec.TEAM_NO,c0rec.MGR_NAME,8,0,0,100,'22-oct-2017',0,'','','','',1187,93844);EXCEPTION
        WHEN OTHERS THEN NULL;
    COMMIT;
    END;
    END IF;
 
--215
  IF c0rec.BRA_CODE <> 215
    THEN    
        BEGIN
        INSERT INTO ACCT_MGR (ACCT_MGR,BRA_CODE,TEAM_NO,MGR_NAME,DEP_CODE,AUT_AMT_DR,AUT_AMT_CR,AUT_LVL,MAT_DATE,SEC_CODE,ALT_ACCT_MGR1,ALT_ACCT_MGR2,ALT_ACCT_MGR3,DEL_DATE,TELL_ID,UPD_TIME)
        VALUES (c0rec.ACCT_MGR,215,c0rec.TEAM_NO,c0rec.MGR_NAME,8,0,0,100,'22-oct-2017',0,'','','','',1187,93844);EXCEPTION
        WHEN OTHERS THEN NULL;
    COMMIT;
    END;
    END IF;

--216
  IF c0rec.BRA_CODE <> 216
    THEN    
        BEGIN
        INSERT INTO ACCT_MGR (ACCT_MGR,BRA_CODE,TEAM_NO,MGR_NAME,DEP_CODE,AUT_AMT_DR,AUT_AMT_CR,AUT_LVL,MAT_DATE,SEC_CODE,ALT_ACCT_MGR1,ALT_ACCT_MGR2,ALT_ACCT_MGR3,DEL_DATE,TELL_ID,UPD_TIME)
        VALUES (c0rec.ACCT_MGR,216,c0rec.TEAM_NO,c0rec.MGR_NAME,8,0,0,100,'22-oct-2017',0,'','','','',1187,93844);EXCEPTION
        WHEN OTHERS THEN NULL;
    COMMIT;
    END;
    END IF;

--217
  IF c0rec.BRA_CODE <> 217
    THEN    
        BEGIN
        INSERT INTO ACCT_MGR (ACCT_MGR,BRA_CODE,TEAM_NO,MGR_NAME,DEP_CODE,AUT_AMT_DR,AUT_AMT_CR,AUT_LVL,MAT_DATE,SEC_CODE,ALT_ACCT_MGR1,ALT_ACCT_MGR2,ALT_ACCT_MGR3,DEL_DATE,TELL_ID,UPD_TIME)
        VALUES (c0rec.ACCT_MGR,217,c0rec.TEAM_NO,c0rec.MGR_NAME,8,0,0,100,'22-oct-2017',0,'','','','',1187,93844);EXCEPTION
        WHEN OTHERS THEN NULL;
    COMMIT;
    END;
    END IF;

--218
  IF c0rec.BRA_CODE <> 218
    THEN    
        BEGIN
        INSERT INTO ACCT_MGR (ACCT_MGR,BRA_CODE,TEAM_NO,MGR_NAME,DEP_CODE,AUT_AMT_DR,AUT_AMT_CR,AUT_LVL,MAT_DATE,SEC_CODE,ALT_ACCT_MGR1,ALT_ACCT_MGR2,ALT_ACCT_MGR3,DEL_DATE,TELL_ID,UPD_TIME)
        VALUES (c0rec.ACCT_MGR,218,c0rec.TEAM_NO,c0rec.MGR_NAME,8,0,0,100,'22-oct-2017',0,'','','','',1187,93844);EXCEPTION
        WHEN OTHERS THEN NULL;
    COMMIT;
    END;
    END IF;
--219
  IF c0rec.BRA_CODE <> 219
    THEN    
        BEGIN
        INSERT INTO ACCT_MGR (ACCT_MGR,BRA_CODE,TEAM_NO,MGR_NAME,DEP_CODE,AUT_AMT_DR,AUT_AMT_CR,AUT_LVL,MAT_DATE,SEC_CODE,ALT_ACCT_MGR1,ALT_ACCT_MGR2,ALT_ACCT_MGR3,DEL_DATE,TELL_ID,UPD_TIME)
        VALUES (c0rec.ACCT_MGR,219,c0rec.TEAM_NO,c0rec.MGR_NAME,8,0,0,100,'22-oct-2017',0,'','','','',1187,93844);EXCEPTION
        WHEN OTHERS THEN NULL;
    COMMIT;
    END;
    END IF;
    --220
  IF c0rec.BRA_CODE <> 220
    THEN    
        BEGIN
        INSERT INTO ACCT_MGR (ACCT_MGR,BRA_CODE,TEAM_NO,MGR_NAME,DEP_CODE,AUT_AMT_DR,AUT_AMT_CR,AUT_LVL,MAT_DATE,SEC_CODE,ALT_ACCT_MGR1,ALT_ACCT_MGR2,ALT_ACCT_MGR3,DEL_DATE,TELL_ID,UPD_TIME)
        VALUES (c0rec.ACCT_MGR,220,c0rec.TEAM_NO,c0rec.MGR_NAME,8,0,0,100,'22-oct-2017',0,'','','','',1187,93844);EXCEPTION
        WHEN OTHERS THEN NULL;
    COMMIT;
    END;
    END IF;

END LOOP;
      
END RM_SETUP_MGRS;

--exec RM_SETUP_MGRS;

--SELECT * FROM ACCT_MGR  WHERE ACCT_MGR IN (1323);
--SELECT * FROM ACCT_MGR  WHERE MGR_NAME NOT IN ('VACANT') ORDER BY ACCT_MGR
